# k8s/hellonode-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode-deployment
  labels:
    app: app-hellonode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hellonode
  template:
    metadata:
      labels:
        app: app-hellonode
    spec:
      containers:
      - name: hellonode
        image: kantmuyu/hellonode:v0
        ports:
        - containerPort: 3001